[default]
input_text_folder           = "data/raw_input_files"

client_source               = "https://75ce65ac-3f32-4f99-9994-130310c38fc1.europe-west3-0.gcp.cloud.qdrant.io"
encoder_name                = "intfloat/e5-base"
collection_name             = "nutrition_faq"

distance_type               = "COSINE"
retrieve_k                  = 5
min_similarity_threshold    = 1.0

llm_model                   = "gpt-4o-mini"
llm_temperature             = 0
llm_system_prompt_path      = "prompts/llm_system_prompt.txt"
